apiVersion: apps/v1
kind: Deployment
metadata:
  name: testw
  labels:
    app: testw
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1727803372386
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testw
  template:
    metadata:
      labels:
        app: testw
    spec:
      containers:
        - name: testw
          image: acrworkflow1727803372386.azurecr.io/image-workflow-1727803372386:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
